export const CALENDAR_EVENT_TYPES = {
  SCHEDULE: "ORARIO",
  TEST: "VERIFICA",
  ORAL_TEST: "INTERROGAZIONE",
  DEADLINE: "CONSEGNA",
  OTHER: "ALTRO",
};

export const CALENDAR_EVENT_PREFIXES = {
  "[ORARIO]": CALENDAR_EVENT_TYPES.SCHEDULE,
  "[VERIFICA]": CALENDAR_EVENT_TYPES.TEST,
  "[INTERROGAZIONE]": CALENDAR_EVENT_TYPES.ORAL_TEST,
  "[CONSEGNA]": CALENDAR_EVENT_TYPES.DEADLINE,
  "[ALTRO]": CALENDAR_EVENT_TYPES.OTHER,
};

export const DEFAULT_CALENDAR_FILTERS = {
  [CALENDAR_EVENT_TYPES.SCHEDULE]: false,
  [CALENDAR_EVENT_TYPES.TEST]: true,
  [CALENDAR_EVENT_TYPES.ORAL_TEST]: true,
  [CALENDAR_EVENT_TYPES.DEADLINE]: true,
  [CALENDAR_EVENT_TYPES.OTHER]: true,
};
